services:
  vault:
    image: hashicorp/vault:latest
    container_name: local_vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault_data:/vault/data
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    command: vault server -config=/vault/config/vault-config.hcl
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK